# Shared camera configuration for LeKiwi robot
wrist:
  type: grayscaleopencv
  index_or_path: /dev/video18
  fps: 30
  width: 640
  height: 480
  rotation: 0
side:
  type: opencv
  index_or_path: /dev/video16
  fps: 30
  width: 640
  height: 480
  rotation: 0
front_left:
    type: imx219single
    camera_idx: 1
    fps: 30
    width: 640
    height: 480
    rotation: 180
front_right:
  type: imx219single
  camera_idx: 0
  fps: 30
  width: 640
  height: 480
  rotation: 180
